name: CI/CD

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, production]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup and Build Backend App
        working-directory: backend
        env:
          DB_CONNECTION: ${{secrets.DB_CONNECTION}}
          JWT_KEY: ${{secrets.JWT_KEY}}
        run: |
          npm ci
          npm run build
          touch build/.env
          echo $DB_CONNECTION >> build/.env
          echo APP_ENV=production >> build/.env
          echo $JWT_KEY >> build/.env
          pm2 restart Thesis

      - name: Setup and Build Frontend App
        working-directory: frontend
        run: |
          npm ci
          touch .env
          echo REACT_APP_API_URL=https://thesis.kaselyakbence.me/api >> .env
          echo GENERATE_SOURCEMAP=false >> .env  
