name: Testing

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, test_runner]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Setup and Test Backend App
        working-directory: backend
        run: |
         npm ci
         npm test


      - name: Setup and Test Frontend App
        working-directory: frontend
        run: |
          npm ci
          npm test
        
